services:
  - type: web
    name: ai-sales-platform
    runtime: node
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    buildCommand: echo "No build needed"
    startCommand: node production.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: IG_VERIFY_TOKEN
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: IG_APP_ID
        sync: false
      - key: IG_APP_SECRET
        sync: false
      - key: BASE_URL
        value: https://ai-instgram.onrender.com
      - key: REDIRECT_URI
        value: ${BASE_URL}/auth/instagram/callback
      - key: CORS_ORIGINS
        value: ${BASE_URL}
    healthCheckPath: /health
    autoDeploy: true