global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@ai-sales-platform.com'
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning  
      receiver: 'warning-alerts'

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://host.docker.internal:10000/webhooks/alerts'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alert-system'
            password: 'change-me-in-production'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:10000/webhooks/alerts/critical'
        send_resolved: true
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          {{ end }}

  - name: 'warning-alerts'
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
        channel: '#alerts'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']